# [START Taraful Turnenii]
runtime: nodejs12

automatic_scaling:
  # 1 instance to control costs
  max_instances: 1
  # maintain a resident instance to avoid startup latency
  min_idle_instances: 1

handlers:
  # static files directory
  - url: /(.*)
    secure: always
    static_files: dist/\1
    # passthrough if file not found
    require_matching_file: true
    upload: dist/.*
  # serve index.html for all remaining i.e. not found
  - url: (.*)
    secure: always
    static_files: dist/index.html
    upload: dist/index.html
