# [START Taraful Turnenii]
runtime: nodejs12

env_variables:
  BUCKET_NAME: "tarafulturnenii-assets"

handlers:
  # static files directory
  - url: /(.*)
    secure: always
    redirect_http_response_code: '301'
    static_files: dist/\1
  # passthrough if file not found
    require_matching_file: true
    upload: dist/.*

  # serve index.html for all remaining i.e. not found
  - url: (.*)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/index.html
    upload:  dist/index.html
