# [START Taraful Turnenii]
runtime: nodejs12
service: default

# Set static file cache time / Avoid loading video BG at default 600s
default_expiration: 3600s

instance_class: F1

automatic_scaling:
  # 1 instance to control costs / Remove when Prod
  max_instances: 1
  # maintain a resident instance to avoid startup latency
  min_idle_instances: 1

# set an entrypoint overriding the default 'npm start'
entrypoint: 'node src/app/server.js'

# set up request handlers
handlers:

## set up app request handlers

# send /send requests to the app
- url: /send
  script: auto

## set up the static file handler

# static files directory
- url: /(.*)
  secure: always
  redirect_http_response_code: '301'
  static_files: dist/\1
  require_matching_file: true
  upload: dist/.*

# serve index.html for all remaining i.e. not found
- url: (.*)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/index.html
  upload:  dist/index.html
# [END Taraful Turnenii]
