runtime: nodejs13

# Static File Cache Time
default_expiration: 600s

automatic_scaling:
  # 1 instance to control costs
  max_instances: 1
  # Maintain a resident instance to avoid startup latency
  min_idle_instances: 1

handlers:

  - url: /(.*)
      static_files: dist/\1
      # passthrough if file not found
      require_matching_file: true
      upload: dist/.*

  - url: (.*)
      static_files: dist/index.html
      upload:  dist/index.html
