runtime: python27
api_version: 1
threadsafe: yes

handlers:

  - url: /(.*\.css)
    static_files: dist/\1
    upload: dist/(.*\.css)

  - url: /(.*\.html)
    static_files: dist/\1
    upload: dist/(.*\.html)

  # Site root.
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  # Catch-all rule, responsible from handling Angular application routes (deeplinks).
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

skip_files:
  - e2e/
  - .idea/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
