runtime: python27
api_version: 1
threadsafe: yes

handlers:

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist

skip_files:
  - e2e/
  - .idea/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
  view rawapp.yaml hosted with ❤ by GitHub
