steps:

  - id: 'Install Node Modules'
    name: node:13.13.0
    entrypoint: npm
    args: ['install']

  - id: 'Run Backend'
    name: node:13.13.0
    entrypoint: npm
    args: ['run', 'backend']

  - id: 'Build --PROD'
    name: node:13.13.0
    entrypoint: npm
    args: ['run', 'build-prod']


  - id: 'Deploy & Go Live'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
